// <auto-generated />
using Ace.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ace.Web.Migrations
{
    [DbContext(typeof(TrackerDBContext))]
    [Migration("20191205213604_RefactorDataFolder")]
    partial class RefactorDataFolder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ace.Web.Core.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNbr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contact","BallotTrack");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            FullName = "Kristen Williams",
                            IsPrimary = true,
                            PhoneNbr = "262-4528"
                        },
                        new
                        {
                            ContactId = 2,
                            FullName = "Megan Rosenberger",
                            IsPrimary = true,
                            PhoneNbr = "256-3245"
                        },
                        new
                        {
                            ContactId = 3,
                            FullName = "Irene Settle",
                            IsPrimary = false,
                            PhoneNbr = "4955896"
                        },
                        new
                        {
                            ContactId = 4,
                            FullName = "Whitney Juszczak",
                            IsPrimary = true,
                            PhoneNbr = "261-8839"
                        },
                        new
                        {
                            ContactId = 5,
                            FullName = "Monica Figueroa",
                            IsPrimary = false,
                            PhoneNbr = "261-8839"
                        },
                        new
                        {
                            ContactId = 6,
                            FullName = "Ben Lane",
                            IsPrimary = true,
                            PhoneNbr = "262-6814"
                        },
                        new
                        {
                            ContactId = 7,
                            FullName = "Elizabeth Martin Parker",
                            IsPrimary = false,
                            PhoneNbr = "261-8749"
                        });
                });

            modelBuilder.Entity("Ace.Web.Core.Step", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StepName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StepId");

                    b.ToTable("Step","BallotTrack");

                    b.HasData(
                        new
                        {
                            StepId = 1,
                            StepName = "Mail Room"
                        },
                        new
                        {
                            StepId = 2,
                            StepName = "Early Voting"
                        },
                        new
                        {
                            StepId = 3,
                            StepName = "Early Ballot Board Verification"
                        },
                        new
                        {
                            StepId = 4,
                            StepName = "Early Ballot Board Ins Ctrl Brd"
                        },
                        new
                        {
                            StepId = 5,
                            StepName = "Tabulation"
                        },
                        new
                        {
                            StepId = 6,
                            StepName = "Completed to Vault"
                        },
                        new
                        {
                            StepId = 7,
                            StepName = "Vault Hold"
                        });
                });

            modelBuilder.Entity("Ace.Web.Core.StepContact", b =>
                {
                    b.Property<int>("StepContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.HasKey("StepContactId");

                    b.HasIndex("ContactId");

                    b.HasIndex("StepId");

                    b.ToTable("StepContact","BallotTrack");

                    b.HasData(
                        new
                        {
                            StepContactId = 1,
                            ContactId = 1,
                            StepId = 1
                        },
                        new
                        {
                            StepContactId = 2,
                            ContactId = 1,
                            StepId = 2
                        },
                        new
                        {
                            StepContactId = 3,
                            ContactId = 3,
                            StepId = 2
                        },
                        new
                        {
                            StepContactId = 4,
                            ContactId = 4,
                            StepId = 3
                        },
                        new
                        {
                            StepContactId = 5,
                            ContactId = 5,
                            StepId = 3
                        },
                        new
                        {
                            StepContactId = 6,
                            ContactId = 4,
                            StepId = 4
                        },
                        new
                        {
                            StepContactId = 7,
                            ContactId = 5,
                            StepId = 4
                        },
                        new
                        {
                            StepContactId = 8,
                            ContactId = 6,
                            StepId = 5
                        },
                        new
                        {
                            StepContactId = 9,
                            ContactId = 7,
                            StepId = 5
                        },
                        new
                        {
                            StepContactId = 10,
                            ContactId = 1,
                            StepId = 6
                        },
                        new
                        {
                            StepContactId = 11,
                            ContactId = 3,
                            StepId = 6
                        },
                        new
                        {
                            StepContactId = 12,
                            ContactId = 1,
                            StepId = 7
                        },
                        new
                        {
                            StepContactId = 13,
                            ContactId = 3,
                            StepId = 7
                        });
                });

            modelBuilder.Entity("Ace.Web.Core.StepContact", b =>
                {
                    b.HasOne("Ace.Web.Core.Contact", "Contact")
                        .WithMany("StepsContact")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ace.Web.Core.Step", "Step")
                        .WithMany("ContactSteps")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
